spring.application.name=assistant
#
spring.datasource.connection-fetch=lazy
spring.datasource.url=jdbc:postgresql://localhost/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
#
spring.ai.bedrock.converse.chat.model=amazon.nova-pro-v1:0
spring.ai.model.embedding=bedrock-cohere
#
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=1024
#
spring.ai.mcp.client.streamable-http.connections.scheduler.url=http://localhost:8081
spring.ai.mcp.client.initialized=false
#
spring.security.oauth2.client.provider.spring.issuer-uri=http://localhost:9090
spring.security.oauth2.client.registration.spring.provider=spring
spring.security.oauth2.client.registration.spring.client-id=spring
spring.security.oauth2.client.registration.spring.client-secret=spring
spring.security.oauth2.client.registration.spring.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.spring.client-authentication-method=client_secret_basic
spring.security.oauth2.client.registration.spring.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.spring.scope=openid,profile
