spring.application.name=auth
spring.docker.compose.lifecycle-management=start_only
#
spring.threads.virtual.enabled=true
#
spring.security.oauth2.authorizationserver.client.messages.registration.client-id=messages
spring.security.oauth2.authorizationserver.client.messages.registration.client-secret={noop}messages
spring.security.oauth2.authorizationserver.client.messages.registration.client-authentication-methods[0]=client_secret_basic
spring.security.oauth2.authorizationserver.client.messages.registration.authorization-grant-types[0]=authorization_code
spring.security.oauth2.authorizationserver.client.messages.registration.authorization-grant-types[1]=client_credentials
spring.security.oauth2.authorizationserver.client.messages.registration.authorization-grant-types[2]=refresh_token
spring.security.oauth2.authorizationserver.client.messages.registration.authorization-grant-types[3]=urn:ietf:params:oauth:grant-type:device_code
spring.security.oauth2.authorizationserver.client.messages.registration.redirect-uris[0]=http://127.0.0.1:8080/login/oauth2/code/messages
spring.security.oauth2.authorizationserver.client.messages.registration.scopes[0]=openid
spring.security.oauth2.authorizationserver.client.messages.registration.scopes[1]=profile
spring.security.oauth2.authorizationserver.client.messages.registration.scopes[2]=email
spring.security.oauth2.authorizationserver.client.messages.registration.scopes[3]=user.write
spring.security.oauth2.authorizationserver.client.messages.registration.scopes[4]=user.read
#
server.port=9090
