spring.application.name=mcp-client
spring.ai.ollama.chat.model=gemma4:26b
#
spring.security.oauth2.client.registration.adoptions.provider=spring
spring.security.oauth2.client.registration.adoptions.client-id=adoptions
spring.security.oauth2.client.registration.adoptions.client-secret=adoptions
spring.security.oauth2.client.registration.adoptions.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.adoptions.client-authentication-method=client_secret_basic
spring.security.oauth2.client.registration.adoptions.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.adoptions.scope[0]=openid
spring.security.oauth2.client.registration.adoptions.scope[1]=profile
#
spring.security.oauth2.client.provider.spring.issuer-uri=http://localhost:9090

spring.ai.mcp.client.streamable-http.connections.scheduler.url=http://localhost:8081
spring.ai.mcp.client.initialized=false