spring.application.name=gateway
spring.security.oauth2.client.provider.spring.issuer-uri=http://localhost:9090
#
spring.security.oauth2.client.registration.messages.provider=spring
spring.security.oauth2.client.registration.messages.client-id=messages
spring.security.oauth2.client.registration.messages.client-secret=messages
spring.security.oauth2.client.registration.messages.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.messages.client-authentication-method=client_secret_basic
spring.security.oauth2.client.registration.messages.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
#
spring.security.oauth2.client.registration.messages.scope[0]=openid
spring.security.oauth2.client.registration.messages.scope[1]=profile
#
logging.level.org.springframework = debug